version: "{build}"

image:
- Visual Studio 2015
- Visual Studio 2017

configuration:
- Debug
- Release

platform:
- 32
- 64

before_build:
- set CXXFLAGS="/permissive- /std:c++latest"

build:
  parallel: true
  verbosity: normal
