version: "{build}"

image:
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013

configuration:
- Debug
- Release

platform:
- 32
- 64

build:
  project: projects\visual-studio\hfsm2.sln
  parallel: true
  verbosity: minimal

test_script:
- cmd: binaries-%PLATFORM%\test-15-%CONFIGURATION%-%PLATFORM%.exe