version: "{build}"

image: Visual Studio 2017

configuration:
- Debug
- Release

platform:
- 32
- 64

build:
  project: projects\visual-studio\HFSM.sln
  parallel: true
  verbosity: minimal

test_script:
- cmd: binaries-64\test-15-Debug-64.exe